# Generated by Django 3.0.3 on 2020-06-13 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=50)),
                ('css_class', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yello'), ('info', 'Turquoise'), ('light', 'light grey'), ('dark', 'Black')], default='string', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('points', models.IntegerField(default=500)),
                ('website', models.URLField(blank=True)),
                ('about', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('experience', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('moderator', 'moderator'), ('normal_user', 'normal_user')], default='normal_user', max_length=50, null=True)),
                ('badges', models.ManyToManyField(blank=True, to='users.Badge')),
                ('favorit_scores', models.ManyToManyField(blank=True, to='archive.Score')),
                ('instruments', models.ManyToManyField(blank=True, to='archive.Instrument')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=25)),
                ('image', models.ImageField(default='default_band.jpg', upload_to='band_pics')),
                ('musicians', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
