# Generated by Django 3.0.3 on 2020-07-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_favorit_music_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorit_music_genres',
        ),
    ]
