# Generated by Django 3.0.3 on 2020-06-13 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('contact', 'contact'), ('request', 'request'), ('add song', 'add song'), ('update song', 'update song'), ('error song', 'error song'), ('add artist', 'add artist'), ('update artist', 'update artist'), ('error artist', 'error artist'), ('add score', 'add score'), ('update score', 'update score'), ('error score', 'error score'), ('add lyric', 'add lyric'), ('update lyric', 'update lyric'), ('error lyric', 'error lyric'), ('error', 'error')], default='uncategorised', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(blank=True)),
                ('state', models.CharField(blank=True, choices=[('created', 'created'), ('processed', 'processed'), ('treated', 'treated'), ('abondanned', 'abondonned'), ('closed', 'closed')], default='created', max_length=50)),
                ('usr_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator_set', to=settings.AUTH_USER_MODEL)),
                ('usr_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_manager_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
