# Generated by Django 3.0.3 on 2020-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_song_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='jins',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='maqam',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='rythm',
            name='sound',
        ),
        migrations.AddField(
            model_name='instrument',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jins',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maqam',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rythm',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
