# Generated by Django 3.0.3 on 2020-07-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20200704_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_msc',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_youtube',
        ),
        migrations.AddField(
            model_name='song',
            name='msc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='ytb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
