# Generated by Django 3.0.3 on 2020-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20200704_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name_orig',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_orig',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lyric',
            name='name_orig',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='name_orig',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='name_orig',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
