# Generated by Django 3.0.3 on 2020-07-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_auto_20200729_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name_orig',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name_orig',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='name_orig',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='name_orig',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='name_orig',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
